# Generated by Django 5.2 on 2025-05-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_personelmodel_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_or_clock', models.CharField(choices=[('D', 'روزانه'), ('C', 'ساعتی')], max_length=5, verbose_name='روزانه یا ساعتی')),
                ('is_accept', models.BooleanField(default=False, verbose_name='تاییدیه')),
                ('is_reject', models.BooleanField(default=False, verbose_name='رد کردن')),
                ('clock_leave_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مرخصی')),
                ('days_start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('days_end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('clock_start_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت شروع')),
                ('clock_end_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='ساعت پایان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.personelmodel', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مرخصی ها',
                'verbose_name_plural': 'مرخصی ها',
            },
        ),
    ]
