# Generated by Django 5.2 on 2025-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelmodel',
            name='access',
            field=models.CharField(choices=[('US', 'کارمند'), ('MO', 'مدیریت')], default='US', max_length=2, verbose_name='سطح دسترسی'),
            preserve_default=False,
        ),
    ]
